# Generated by Django 4.1 on 2022-08-04 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante', verbose_name='Restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valo_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('status', models.CharField(choices=[(1, 'Aberto'), (2, 'Recebido'), (3, 'Em preparo'), (4, 'Saiu para entrega')], max_length=25, verbose_name='Descrição')),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.restaurante', verbose_name='Restaurante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total')),
                ('obs', models.CharField(max_length=255, verbose_name='Observação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.produto', verbose_name='Produto')),
            ],
        ),
    ]
