# Generated by Django 4.1 on 2022-08-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valo_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
