# Generated by Django 4.1 on 2022-08-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_itempedido_options_alter_pedido_valo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valo_total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
