# Generated by Django 4.1 on 2022-08-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
